site_name: sparse
repo_url: https://github.com/pydata/sparse.git
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.svg
  features:
        - toc.integrate
        - navigation.tracking
        - navigation.instant
        - navigation.prune
        - navigation.tabs
        - navigation.footer
markdown_extensions:
  - tables
  - pymdownx.superfences
  - toc:
      toc_depth: 2

plugins:
- search
- section-index
- autorefs
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav
- mkdocstrings:
    handlers:
          python:
            import:
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            options:
              inherited_members: yes
              show_root_members_full_path: false
              show_if_no_docstring: false
              members_order: source
              docstring_style: numpy
              filters: ["!^_"]
nav:
- index.md
- install.md
- quickstart.md
- construct.md
- operations.md
- API:
  - api/*
- roadmap.md
- contributing.md
- changelog.md
- conduct.md
