site_name: sparse
repo_url: https://github.com/pydata/sparse.git
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.svg
  features:
        - toc.integrate
        - navigation.tracking
        - navigation.instant
        - navigation.tabs
        - navigation.footer
markdown_extensions:
  - tables
  - toc:
      toc_depth: 2

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
          python:
            options:
              inherited_members: yes
              members_order: alphabetical
              filters:
              - "!^_+"
nav:
- index.md
- install.md
- quickstart.md
- construct.md
- operations.md
- API:
    - api/*
- roadmap.md
- contributing.md
- changelog.md
- conduct.md
